Lab2: ReadMe
Rigorich/QuizDeRigorich pull request #2
Opened 2022-04-03 16:59 UTC by Rigorich

2022-04-03 18:22 UTC, Nastik1811 commented
А дзе аўтарызацыя, меню, з якога можна перайсці да стварэння або да прахождання квіза, спіс даступных квізаў і старонка з вынікамі? 
![image](https://user-images.githubusercontent.com/37243282/161442210-c5e9d56d-9912-418f-b615-448dc1af7b6e.png)

2022-04-03 18:25 UTC, Nastik1811 commented
І яшчэ трэба паказваць нейкі прагрэсс праходжання квізу

2022-04-03 18:27 UTC, Nastik1811 commented
На якой мове вам зручней атрымліваць каментарыі?)

2022-04-03 18:28 UTC, Nastik1811 commented
Наколькі я разумею, павінна быць магчымасць загружаць карцінку
<img width="358" alt="image" src="https://user-images.githubusercontent.com/37243282/161442625-0be0f7ba-f8a8-4a4c-8cea-f87c0d30bcfb.png">

2022-04-03 18:37 UTC, Nastik1811 commented
І яшчэ. Калі юзер клікае па адказу, ён адразу submit'іцца? 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/37243282/161442928-e6339eba-5fd4-4a6f-85cb-04cd06a87214.png">

2022-04-03 18:39 UTC, Nastik1811 commented
Проста улічваючы, што гэта чэкбоксы, у вас можа быць некалькі варыянтаў адказу. (Калі ўсё ж адзін, то зрабіце гэта з дапамогай радыё кнопак)
<img width="244" alt="image" src="https://user-images.githubusercontent.com/37243282/161442995-83456927-898d-4e6b-b01a-6eb9bf1d477a.png">

2022-04-03 18:44 UTC, Nastik1811 commented
А, там розныя тыпы пытанняў ёсць... Штош, у ідэале паказаць як будзе выглядаць форма і праходжанне для ўсіх тыпаў))

2022-04-03 18:47 UTC, Nastik1811 requested changes
Тое, што ёсць, зроблена добра, але трэба дарабляць

2022-04-03 18:57 UTC, Rigorich commented
Сори, на другие страницы бюджет не выделили)

Прогресс показывать... ладненько, придумаем-с

Читать комментарии могу в любом виде, отвечать предпочту на русском

Добавить вид без загруженного изображения, ладушки

Ответ будет отсылаться по истечении времени для всех типов вопросов
Надо бы добавить выделение выбранного(-ых) ответов, да

Чекбоксы как раз для множественных ответов, но красиво выглядят и на одиночном, поэтому не хотел бы использовать радиобатон

Ых, надо бы добавить ещё вид открытого вопроса, да

2022-04-22 11:03 UTC, Nastik1811 commented
Дык што там па прагрэсу?

2022-04-22 19:21 UTC, Rigorich commented
> Дык што там па прагрэсу?

Понимание бессмысленности предварительного дизайна вызвало у меня полезную прокрастинацию, из-за чего я переключился на лабы по другим предметам и непосредственному кодингу проекта

Когда-нибудь вернусь и к дизайну. Надеюсь.

2022-04-23 13:13 UTC, Nastik1811 commented
<img width="109" alt="image" src="https://user-images.githubusercontent.com/37243282/164896036-fdc8d49b-3bf9-42d1-94a7-cf8e94e56664.png">

2022-04-29 15:41 UTC, Nastik1811 approved these changes
`8`

2022-04-29 15:44 UTC, merged